language: php
php:
- '7.2'
install:
- composer install --prefer-dist --optimize-autoloader --quiet
script: phpunit -c phpunit.xml
notifications:
  slack:
    secure: KJxvq5gL6mRLWGm0HUe6MX1wSPe1gl/S6LYUmVBE3SFEMEcfV6k8OHyoB7fAtctJUuTYIg0wtbWyoqgLUp0/E1SfQreIHiBKlPJqKPG9TghnMztNpXrfg5FncCkQaVKwtZosa4uls3f0S7mDsXvWiu54Hwjt8bbx9ADTSpEECGbqs9PzfF+y3RHAOxItD0eN4I4TqU44pluV9SK4x93skMVQ90Lz4Nlj+7u+n8snUOPdRSZ3PfhtWy6OFHiFb9AorEIWLBlqWH3Xi+TIbWcy4N5AXUyA14mUdQ/BxjoQTivlNxkVtEBueJEWfOb+mb7dASg8KJKyQYp5dN1RcK0AVzNf9FpwqAt2GBuxtC8NR4Fe15wzU5WM7fLdx4hlZMQnjUJ3W1wVE7C1oWrWCelD9A2VIY6qrxVnk/PaePaE2F1p29W9YtkaiRj/tKZEHpTTd04UCCd2IfF2FmJ0ennXr+LrGKJnl6GbDWNoEgqjmS8RGILcMx80XP3L1mLA2tdwy3KlqkIS66feowKI0dUfb/aPEtcWIluPTTq0uWnH6nlqSN/pcASjLKsv0xnFFq8+ijnRW0RvvqFb11QICVJxGVzJs/BqkPxSgmOmu6QT5DoI2VfXeUyt1+c4abtnFsqCdS7lfK+o4Gf1EZ7qqMnzf4JpXLVukYAbc2bgAR6p7rw=
